### ISSUE TITLE
你好，请问下保存的深度信息是什么格式的？

### ISSUE THREAD

**Issue by enjoybo** [mantoone/DepthCapture#1]
Hi, Thanks for your great work. I want to save the recorded video and the depth data simultaneously in one kind of video. So in this project did you save the depth data frame by frame or just encode the depth data into the  recorded video?

**Comment by mantoone** [comment]
Hi, thanks for checking out my repo. In this project the RGB video and depth data are saved to two different files. And the file containing depth information has the depth data as frames. So unfortunately this project doesn’t give you a single video containing both the pixels and depth data.

**Comment by soichiro230** [comment]
Thanks for the wonderful work
I exported the depth data to a video file, but failed to restore using VFXGraph in Unity on Windows.
Have you ever restored depth videos to 3D?

**Comment by mantoone** [comment]
Nice to hear you found this repo useful. How did you export the depth data to a video file? I have only used the approach shown in the notebook in this repo, that is, reading the compressed depth data file.

**Comment by soichiro230** [comment]
I have a separate video along with your notebook.
It works fine and outputs a grayscale video, but I can't successfully restore it to 3D in Unity.

**Comment by mantoone** [comment]
Ok, I see. What kind of format does Unity need? Do they state that grayscale video works? One potential problem could be that the RGB video and the depth video may not have the same number of frames (if you try to use both in Unity). I couldn't find a way to make the iOS app record video and for each RGB video frame also capture a depth frame. They are done asynchronously.
