### ISSUE TITLE
What is the range limitation of truedepth sensor on iphone?

### ISSUE THREAD

**Issue by pramishp** [mantoone/DepthCapture#2]
This may not be the right issue for this project. But if someone knows, can you share the details about this.

**Comment by mantoone** [comment]
Maybe this paper helps https://www.researchgate.net/publication/335876093_Measurement_accuracy_and_dependence_on_external_influences_of_the_iPhone_X_TrueDepth_sensor it’s for iPhone X, however, so some things may have changed in the latest models.
