### ISSUE TITLE
Reading depth data?

### ISSUE THREAD

**Issue by sanamsta** [mantoone/DepthCapture#3]
How to play or read the depth data from saved depth data?

**Comment by mantoone** [comment]
Are you familiar with Python and Jupyter? There’s an example Jupyter notebook for reading the depth data in the notebooks folder. You can also use it to create a depth video file.

**Comment by sanamsta** [comment]
Thanks,

**Comment by sanamsta** [comment]
Actually i dont want to create depth video i just want to read it in swift. I want to get per frame depth information from file.Do you have any idea how to get that?

**Comment by mantoone** [comment]
Unfortunately, I have not done that myself so I don’t know how to fo it right away. The depth data saving is based on Eyal Fink’s code which can be found here https://stackoverflow.com/a/50265132

That should be a good starting point. You can search what you can use to decompress files that have been compressed as shown in the code, that is, using:
compression_stream_init(compresserPtr!, COMPRESSION_STREAM_ENCODE, COMPRESSION_ZLIB)
Or you may try to use zlib in C read it and use inflateInit2(&strm, -15): as Eyal suggested.

**Comment by sanamsta** [comment]
Thanks
